services:
  delivery_boy_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../frontend:/frontend
      - ../backend:/backend
    ports:
      - "8080:5001"
    
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
    command: >
      sh -c "sleep 10 && pip install -r requirements.txt &&
             flask run --host=0.0.0.0 --port=5001"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1

    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 10s
      retries: 10

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 30s
      retries: 10

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: delivery_boy_tracking
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 30s
      retries: 10

volumes:
  mysql_data:
