"""empty message

Revision ID: 840fa9806624
Revises: 
Create Date: 2024-10-18 15:46:50.383598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840fa9806624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_boy_id', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_updates')
    # ### end Alembic commands ###
