"""empty message

Revision ID: f7ab21775df5
Revises: 840fa9806624
Create Date: 2024-10-18 16:00:34.797532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7ab21775df5'
down_revision = '840fa9806624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_updates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_updates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
